server:
  port: 8087

spring:
  application:
    name: shc

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-shc}:3306/sps_shc_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:10.43.100.122}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:admin123}
    virtual-host: /

sps:
  cola:
    shc: ColaSHC

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    "[com.sps.shc]": INFO
