server:
  port: 8090

spring:
  application:
    name: sps-sns
  profiles:
    active: production
  datasource:
    url: jdbc:h2:mem:sns-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[co.sps.sns]": INFO
    "[org.springframework.web]": WARN
