server:
  port: 8080

spring:
  application:
    name: sps-balanceador
  profiles:
    active: production
  webflux:
    base-path: /
  datasource:
    url: jdbc:mysql://mysql-balanceador:3306/sps_balanceador_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

balanceador:
  backends:
    - http://10.43.100.122:8081
    - http://10.43.99.121:8081
  healthcheck:
    interval-ms: 15000

sns:
  base-url: http://10.43.101.18:8090
  timeout-ms: 5000
  max-retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[co.sps.balanceador]": INFO
    "[org.springframework.web.reactive]": WARN
