server:
  port: 8081

spring:
  application:
    name: sam

  datasource:
    url: jdbc:mysql://localhost:3309/sps_sam_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true