server:
  port: 8084

spring:
  application:
    name: sps-email
  profiles:
    active: production
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-email}:3306/sps_email_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

email:
  from: ${MAIL_USER}
  salud-pay-url: ${SALUD_PAY_URL:http://10.43.100.111:5000}
  sps-url-pago: ${SPS_URL_PAGO:http://10.43.100.111:4201/pago}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[co.sps.email]": INFO
    "[org.springframework.mail]": WARN
