server:
  port: 8084

spring:
  application:
    name: sps-email
  profiles:
    active: production
  datasource:
    url: jdbc:h2:mem:email-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

email:
  from: ${MAIL_USER}
  salud-pay-url: ${SALUD_PAY_URL:http://10.43.101.18:8080}
  sps-url-pago: ${SPS_URL_PAGO:http://10.43.101.18:4200/pago}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[co.sps.email]": INFO
    "[org.springframework.mail]": WARN
