worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream ms_compra_pool {
        server 10.43.100.111:8082 weight=2;
        server 10.43.99.121:8082 weight=1;
        server 10.43.99.121:8083 weight=1;
        max_fails 3;
        fail_timeout 3s;
        keepalive 30;
    }

    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;
        server_name 10.43.100.122;

        location /health {
            access_log off;
            return 200 '{"status":"UP","node":"Core-A","role":"balancer"}';
            add_header Content-Type application/json;
        }

        location /api/compra/ {
            proxy_pass http://ms_compra_pool/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "";
            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        location /api/auth/ {
            proxy_pass http://10.43.100.122:8081/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 10s;
            proxy_read_timeout 30s;
        }

        location /api/catalogo/ {
            proxy_pass http://10.43.100.122:8081/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 10s;
            proxy_read_timeout 30s;
        }

        error_page 502 503 504 /50x.html;
        location = /50x.html {
            return 503 '{"error":"Servicio temporalmente no disponible"}';
            add_header Content-Type application/json;
        }
    }
}
