server:
  port: 8081

spring:
  application:
    name: ms-compra

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-compra}:${DB_PORT:3306}/sps_compra_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:10.43.100.122}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:admin123}
    virtual-host: /

sps:
  cola:
    pago: ColaPagoConfirmado
    sam: ColaSAM
    shc: ColaSHC

sns:
  base-url: ${SNS_URL:http://10.43.101.18:8090}
  codigo-aseguradora: ${SNS_CODIGO:ASEG001}
  timeout-ms: 5000
  polling-ms: 15000

email:
  base-url: ${EMAIL_URL:http://10.43.101.18:8084}
  sps-url-pago: ${SPS_URL_PAGO:http://10.43.100.111:4201/pago}

saludpay:
  base-url: ${SALUD_PAY_URL:http://10.43.100.111:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[com.sps.compra]": INFO
