server:
  port: 8090

spring:
  application:
    name: sps-sns
  profiles:
    active: production
  datasource:
    url: jdbc:mysql://10.43.101.18:3306/sps_sns?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sps_user
    password: sps_pass_CAMBIAR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[co.sps.sns]": INFO
    "[org.springframework.web]": WARN
